"""
Heuristic Fallback Engine — Graceful degradation when LLM is unavailable.

When the circuit breaker is OPEN or all retries fail, we don't crash.
We fall back to deterministic rule-based detection. Less smart, but always available.

This is a CRITICAL safety net for an offline security system.
"""

from typing import Any

from loguru import logger

from validation.schemas import (
    ActionType, AgentName, Evidence, Finding, Location, ThreatLevel
)


class HeuristicEngine:
    """Deterministic rule-based threat detection. Used as fallback only."""

    # ============================================================
    # Process-based heuristics (Resource Warden fallback)
    # ============================================================

    def evaluate_process(
        self, proc: dict[str, Any], red_flags: list[str]
    ) -> Finding | None:
        """Rule-based process verdict. No LLM involved."""
        score = 0
        evidence_items = []

        # Each red flag contributes to the score
        flag_weights = {
            "high_cpu": 1,
            "high_mem": 1,
            "signal=": 4,                    # encoded PowerShell, etc.
            "risky_location=": 3,
            "office_spawned_powershell": 5,  # very strong indicator
        }

        for flag in red_flags:
            for prefix, weight in flag_weights.items():
                if flag.startswith(prefix):
                    score += weight
                    evidence_items.append(flag)
                    break

        # Threshold-based classification
        if score >= 7:
            level = ThreatLevel.CRITICAL
            action = ActionType.QUARANTINE
            confidence = 0.85
        elif score >= 5:
            level = ThreatLevel.HIGH
            action = ActionType.ALERT
            confidence = 0.75
        elif score >= 3:
            level = ThreatLevel.MEDIUM
            action = ActionType.WATCH
            confidence = 0.6
        elif score >= 1:
            level = ThreatLevel.LOW
            action = ActionType.WATCH
            confidence = 0.4
        else:
            return None  # nothing notable

        try:
            location = Location(
                pid=proc.get("pid"),
                process_name=proc.get("name"),
                file_path=proc.get("exe"),
            )
        except ValueError:
            return None  # not enough data to identify

        return Finding(
            agent_name=AgentName.RESOURCE_WARDEN,
            threat_level=level,
            title=f"Heuristic alert: {proc.get('name', 'unknown')}",
            description=(
                f"Heuristic engine detected {len(evidence_items)} red flag(s) "
                f"on process {proc.get('name')} (PID {proc.get('pid')}). "
                f"This finding was generated by rules — LLM was unavailable. "
                f"Manual review recommended."
            ),
            location=location,
            evidence=Evidence(
                raw_data={"process": proc, "score": score},
                red_flags=evidence_items,
                reasoning=f"Rule-based score: {score}. LLM fallback active.",
            ),
            confidence=confidence,
            recommended_action=action,
            mitre_techniques=self._infer_mitre(red_flags),
        )

    def _infer_mitre(self, red_flags: list[str]) -> list[str]:
        """Map red flags to MITRE ATT&CK techniques."""
        mappings = {
            "office_spawned_powershell": ["T1059.001", "T1566.001"],  # PS execution + spearphishing
            "signal=powershell.exe -enc": ["T1059.001", "T1027"],     # Obfuscated execution
            "signal=rundll32.exe": ["T1218.011"],                     # Signed binary proxy
            "signal=regsvr32.exe": ["T1218.010"],
            "signal=mshta.exe": ["T1218.005"],
            "risky_location=": ["T1547"],                              # Persistence
        }

        techniques = set()
        for flag in red_flags:
            for key, mapped in mappings.items():
                if flag.startswith(key):
                    techniques.update(mapped)
        return list(techniques)

    # ============================================================
    # File-based heuristics (Cyber Analyst fallback)
    # ============================================================

    def evaluate_file(
        self,
        file_path: str,
        sha256: str,
        yara_matches: list[str],
        pe_anomalies: list[str],
    ) -> Finding | None:
        """Rule-based file verdict."""
        score = len(yara_matches) * 4 + len(pe_anomalies) * 2

        if score == 0:
            return None

        if score >= 8:
            level = ThreatLevel.CRITICAL
            action = ActionType.QUARANTINE
            confidence = 0.9
        elif score >= 4:
            level = ThreatLevel.HIGH
            action = ActionType.QUARANTINE
            confidence = 0.75
        else:
            level = ThreatLevel.MEDIUM
            action = ActionType.WATCH
            confidence = 0.55

        try:
            location = Location(
                file_path=file_path,
                file_hash_sha256=sha256 if len(sha256) == 64 else None,
            )
        except ValueError:
            return None

        return Finding(
            agent_name=AgentName.CYBER_ANALYST,
            threat_level=level,
            title=f"Heuristic file alert: {file_path.split('/')[-1].split(chr(92))[-1]}",
            description=(
                f"YARA matches: {len(yara_matches)}; PE anomalies: {len(pe_anomalies)}. "
                f"LLM fallback active — generated by rules only."
            ),
            location=location,
            evidence=Evidence(
                raw_data={
                    "yara_matches": yara_matches,
                    "pe_anomalies": pe_anomalies,
                    "score": score,
                },
                red_flags=yara_matches + pe_anomalies,
                reasoning="Rule-based scoring without LLM reasoning.",
            ),
            confidence=confidence,
            recommended_action=action,
            mitre_techniques=[],
        )

    # ============================================================
    # Network-based heuristics (Traffic Observer fallback)
    # ============================================================

    def evaluate_connection(
        self,
        conn: dict[str, Any],
        ioc_match: bool,
        suspicious_port: bool,
    ) -> Finding | None:
        """Rule-based network verdict."""
        if not (ioc_match or suspicious_port):
            return None

        if ioc_match:
            level = ThreatLevel.CRITICAL
            action = ActionType.BLOCK_NETWORK
            confidence = 0.95
            reason = "Connection to known C2 server (IOC match)"
        else:
            level = ThreatLevel.MEDIUM
            action = ActionType.WATCH
            confidence = 0.5
            reason = f"Suspicious port: {conn.get('remote_port')}"

        try:
            location = Location(
                pid=conn.get("pid"),
                remote_ip=conn.get("remote_ip"),
                remote_port=conn.get("remote_port"),
            )
        except ValueError:
            return None

        return Finding(
            agent_name=AgentName.TRAFFIC_OBSERVER,
            threat_level=level,
            title="Heuristic network alert",
            description=f"{reason}. LLM fallback active.",
            location=location,
            evidence=Evidence(
                raw_data={"connection": conn},
                red_flags=[reason],
            ),
            confidence=confidence,
            recommended_action=action,
            mitre_techniques=["T1071"] if ioc_match else [],  # C2 communication
        )
